
package cop5556sp17;

import cop5556sp17.AST.ASTNode;
import cop5556sp17.AST.Program;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import java.lang.reflect.InvocationTargetException;

import static junit.framework.TestCase.assertEquals;

public class CodeGenVisitorTest {

	static final boolean doPrint = true;
	static void show(Object s) {
		if (doPrint) {
			System.out.println(s);
		}
	}

	boolean devel = false;
	boolean grade = true;


	@Test
	public void emptyProg() throws Exception {
		//scan, parse, and type check the program
		String progname = "emptyProg";
		String input = progname + "  {}";
		Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);
		show(program);

		//generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
		byte[] bytecode = (byte[]) program.visit(cv, null);

		//output the generated bytecode
		CodeGenUtils.dumpBytecode(bytecode);

		//write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = new String[0]; //create command line argument array to initialize params, none in this case
		Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
		instance.run();
	}

	@Test
	public void prog2() throws Exception {
		//scan, parse, and type check the program
		String progname = "prog2";
		String input = progname + "  {integer i i<-3; while(i<10){ i <- i + 2;}}";
		Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);
		show(program);

		//generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
		byte[] bytecode = (byte[]) program.visit(cv, null);

		//output the generated bytecode
		CodeGenUtils.dumpBytecode(bytecode);

		//write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = new String[0]; //create command line argument array to initialize params, none in this case
		Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
		instance.run();
	}

	@Test
	public void prog3() throws Exception {
		//scan, parse, and type check the program
		String progname = "prog3";
		String input = progname + " {integer a \n boolean v \n integer d \n a <- 20; \n v <- true; \n d <- a + 20;}";
		Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);
		show(program);

		//generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
		byte[] bytecode = (byte[]) program.visit(cv, null);

		//output the generated bytecode
		CodeGenUtils.dumpBytecode(bytecode);

		//write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = new String[0]; //create command line argument array to initialize params, none in this case
		Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
		instance.run();
	}

	@Test
	public void prog4() throws Exception {
		//scan, parse, and type check the program
		String progname = "prog4";
		String input = progname + " integer x, boolean b {b <- false; x <- 1;}";
		Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);
		show(program);

		//generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
		byte[] bytecode = (byte[]) program.visit(cv, null);

		//output the generated bytecode
		CodeGenUtils.dumpBytecode(bytecode);

		//write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = new String[]{"2", "true"}; //create command line argument array to initialize params, none in this case
		Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
		instance.run();
	}

	@Test
	public void prog5() throws Exception {
		//scan, parse, and type check the program
		String progname = "prog5";
		String input = progname + " {integer a boolean b if(true) {a<-4+5;}}";
		Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);
		show(program);

		//generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
		byte[] bytecode = (byte[]) program.visit(cv, null);

		//output the generated bytecode
		CodeGenUtils.dumpBytecode(bytecode);

		//write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = new String[0]; //create command line argument array to initialize params, none in this case
		Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
		instance.run();
	}
	@Test
	public void prog6() throws Exception {
		//scan, parse, and type check the program
		String progname = "prog6";
		String input = progname + " {boolean a boolean b b<-true; while(10<10) {a<-true;}}";
		Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);
		show(program);

		//generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
		byte[] bytecode = (byte[]) program.visit(cv, null);

		//output the generated bytecode
		CodeGenUtils.dumpBytecode(bytecode);

		//write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = new String[0]; //create command line argument array to initialize params, none in this case
		Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
		instance.run();
	}

	@Test
	public void prog7() throws Exception {
		//scan, parse, and type check the program
		String progname = "prog7";
		String input = progname + " {boolean x boolean y integer z x<-false; y<-true; if(x|y){ z<-10;}}";
		Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);
		show(program);

		//generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
		byte[] bytecode = (byte[]) program.visit(cv, null);

		//output the generated bytecode
		CodeGenUtils.dumpBytecode(bytecode);

		//write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = new String[0]; //create command line argument array to initialize params, none in this case
		Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
		instance.run();
	}

	@Test
	public void testLoadImageFromFile() throws Exception {
		String progname = "testLoadImageFromFile";
        String input = progname + " file f{image img \n f -> img;} ";
        Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);
        show(program);

		// generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

		byte[] bytecode = (byte[]) program.visit(cv, null);

		CodeGenUtils.dumpBytecode(bytecode);

		// write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = {"bin/Oregon1.JPG"}; //
		try {
			Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
			instance.run();
		} catch (InvocationTargetException e) {
			e.printStackTrace();
			throw e;
		}
	}

    @Test
    public void testBinaryAddImage() throws Exception {
        String progname = "testBinaryAddImage";
        String input = progname + " file f1, file f2, file f3{" +
                "image img1 \n f1 -> img1; \n image img2 \n" +
                "f2 -> img2; image img3 img3 <- img1 + img2;\n" +
                "img3 -> f3;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image.jpg", "bin/image1.jpg", "bin/imgAdd.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testBinarySubImage() throws Exception {
        String progname = "testBinarySubImage";
        String input = progname + " file f1, file f2, file f3{" +
                "image img1 \n f1 -> img1; \n image img2 \n" +
                "f2 -> img2; image img3 img3 <- img1 - img2;\n" +
                "img3 -> f3;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image.jpg", "bin/image1.jpg", "bin/imgSub.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testBinaryMulImage() throws Exception {
        String progname = "testBinaryMulImage";
        String input = progname + " file f1, file f2, file f3{" +
                "image img1 \n f1 -> img1; \n image img2 \n" +
                "f2 -> img2; image img3 img3 <- img1 * 2;\n" +
                "img3 -> f3;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image.jpg", "bin/image1.jpg", "bin/imgMul.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testBinaryDivImage() throws Exception {
        String progname = "testBinaryDivImage";
        String input = progname + " file f1, file f2, file f3{" +
                "image img1 \n f1 -> img1; \n image img2 \n" +
                "f2 -> img2; image img3 img3 <- img1 / 5;\n" +
                "img3 -> f3;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image.jpg", "bin/image1.jpg", "bin/imgDiv.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testBinaryModImage() throws Exception {
        String progname = "testBinaryModImage";
        String input = progname + " file f1, file f2, file f3{" +
                "image img1 \n f1 -> img1; \n image img2 \n" +
                "f2 -> img2; image img3 img3 <- img1 % 3;\n" +
                "img3 -> f3;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image.jpg", "bin/image1.jpg", "bin/imgMod.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testChain() throws Exception {
        String progname = "testChain";
        String input = progname + " file f1, file f2 {image i \n f1 -> i; \n i -> blur -> f2;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image.jpg", "bin/imgOut.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testExtendedChain() throws Exception {
        String progname = "testExtendedChain";
        String input = progname + " file f1, file f2 {image i \n f1 -> i; \n " +
                "i -> blur -> convolve -> gray -> f2;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image.jpg", "bin/imgOut1.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testFrames() throws Exception {
        String progname = "testFrames";
        String input = progname + " file f1{" +
                " image i frame fr f1 -> i;" +
                " i -> fr; \n" +
                " fr -> show; \n" +
                " sleep(1000);}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image1.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testLoadImageFromUrl() throws Exception {
        String progname = "testLoadImageFromUrl";
        String input = progname + " url u {" +
                "image img \n " +
                "u -> img;\n" +
                "frame fr img -> fr -> show;\n" +
                "sleep(1000);\n " +
                "fr -> hide;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testFramesExtended() throws Exception {
        String progname = "testFramesExtended";
        String input = progname + " file f1, file f2 {" +
                " image i frame fr f1 -> i;" +
                " i -> scale(3) -> i; \n" +
                " i -> fr; \n" +
                " fr -> show; \n" +
                " sleep(1000); \n" +
                " fr -> hide;\n" +
                " i -> f2;} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image1.jpg", "bin/imgOut1.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testFramesExtended2() throws Exception {
        String progname = "testFramesExtended2";
        String input = progname + " file f1{" +
                " image i frame fr f1 -> i;" +
                " i -> fr; \n" +
                " fr -> show; \n" +
                "sleep(1000); \n" +
                " fr -> hide; \n" +
                " i -> gray -> fr; \n" +
                " fr -> show; \n" +
                " sleep(1000);}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image1.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void testFrameOperations() throws Exception {
        String progname = "testFrameOperations";
        String input = progname + " file f, url u { \n"
                + "integer i1 integer i2 image img1 image img2 frame fr\n"
                + "f -> img1;\n"
                + "u -> img1;\n"
                + "img1->img2;\n"
                + "img1-> fr-> show -> move(screenwidth, screenheight); \n"
                + "sleep(1000); fr -> hide;\n"
                + "fr -> xloc -> i1;\n"
                + "fr -> yloc -> i2;\n"
                + "img1 -> fr -> show -> move(i1 - 1000, i2 - 1200); \n"
                + "sleep(1000);}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        program.visit(v, null);
        show(program);

        // generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);

        byte[] bytecode = (byte[]) program.visit(cv, null);

        CodeGenUtils.dumpBytecode(bytecode);

        // write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = {"bin/image1.jpg",
                "http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"};
        try {
            Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
            instance.run();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    public void progProf1() throws Exception {
        //scan, parse, and type check the program
        String input = "subImage url u {image i image j image k frame f \nu -> i; \nu -> j; \n k <- i-j; k -> f -> show;\n} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)subcopyImagecreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf2() throws Exception {
        //scan, parse, and type check the program
        String input = "readFromURLandWriteToFile2 url u, \nfile out \n{image i frame f \nu -> gray  -> i;\n i -> f -> show; \n i -> out;\n} ";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg", "bin/imgOut2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)subcopyImagecreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
//        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf3() throws Exception {
        //scan, parse, and type check the program
        String input = "sleepImg url u {image i frame f \nu -> i -> convolve -> f -> show;sleep 5;integer j j <- 42;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)convolvecreateOrSetFrameshowImage42";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf4() throws Exception {
        //scan, parse, and type check the program
        String input = "addImage url u {image i image j image k frame f \nu -> i; \nu -> j; \n k <- i-j; k -> f -> show;  sleep 5; k <- k + i; k -> f -> show; \n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)subcopyImagecreateOrSetFrameshowImageaddcopyImagecreateOrSetFrameshowImageshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf5() throws Exception {
        //scan, parse, and type check the program
        String input = "convolveImg url u {image i frame f \nu -> i -> convolve -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)convolvecreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf6() throws Exception {
        //scan, parse, and type check the program
        String input = "readFromURLandDisplay url u {image i frame f \nu -> i;i -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)createOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf7() throws Exception {
        //scan, parse, and type check the program
        String input = "imgMove2 url u {image i frame f \nu -> i;i -> f -> show; \nsleep 5; \ninteger x \ninteger y \nx <- screenwidth;\ny <-  screenheight; \nf -> move (x*3/4,y/4) -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)createOrSetFrameshowImagegetScreenWidth1280getScreenHeight800moveFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf8() throws Exception {
        //scan, parse, and type check the program
        String input = "subImage2 url u {image i image j  frame f \nu -> i; \nu -> j; \n i <- i-j; i -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)subcopyImagecreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf9() throws Exception {
        //scan, parse, and type check the program
        String input = "modImage url u {image i image j  frame f \nu -> j; \n i <- j%128; i -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)modcopyImagecreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf10() throws Exception {
        //scan, parse, and type check the program
        String input = "allTheOps file u {image i frame f \nu -> i -> gray -> convolve -> blur -> i -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"bin/image.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "readFromFile(bin/image.jpg)grayOpconvolveblurOpcreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf11() throws Exception {
        //scan, parse, and type check the program
        String input = "readFromURLandDisplayDisplay2 url u {image i frame f \nu -> i -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)createOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf12() throws Exception {
        //scan, parse, and type check the program
        String input = "readFromURLandWriteToFile url u, \nfile out \n{image i frame f \nu -> i;i -> f -> show; \n i -> out;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg", "bin/out.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)createOrSetFrameshowImagewrite(bin/out.jpg)";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf13() throws Exception {
        //scan, parse, and type check the program
        String input = "blurImg url u {image i frame f \nu -> i -> blur -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)blurOpcreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf14() throws Exception {
        //scan, parse, and type check the program
        String input = "grayImg url u {image i frame f \nu -> i -> gray -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)grayOpcreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf15() throws Exception {
        //scan, parse, and type check the program
        String input = "divImage url u {image i image j  frame f \nu -> j; \n i <- j/2; i -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)divcopyImagecreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf16() throws Exception {
        //scan, parse, and type check the program
        String input = "readFromURLandWriteScaledImageToFile url u, \nfile out \n{image i frame f \nu -> scale (3) -> i;i -> f -> show; \n i -> out;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg", "bin/out1.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)scalecreateOrSetFrameshowImagewrite(bin/out1.jpg)";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf17() throws Exception {
        //scan, parse, and type check the program
        String input = "readFromFile file u {image i frame f \nu -> i;i -> f -> show; \n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"bin/image.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "readFromFile(bin/image.jpg)createOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf18() throws Exception {
        //scan, parse, and type check the program
        String input = "barArrowGray url u {image i frame f \nu -> i |-> gray -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)grayOpcreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf19() throws Exception {
        //scan, parse, and type check the program
        String input = "assignImage url u {image i image j frame f \nu -> i; j <- i;j -> f -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)copyImagecreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf20() throws Exception {
        //scan, parse, and type check the program
        String input = "scaleImage url u {image i frame f \nu -> i -> f -> show; frame f2  \ni -> scale (3) -> f2 -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)createOrSetFrameshowImagescalecreateOrSetFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf21() throws Exception {
        //scan, parse, and type check the program
        String input = "imgMove url u {image i frame f \nu -> i;i -> f -> show; \nsleep 5; \ninteger x \ninteger y \nf -> xloc -> x; \nf -> yloc -> y; \nf -> move (x+100,y-100) -> show;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)createOrSetFrameshowImagegetXgetYmoveFrameshowImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }

    @Test
    public void progProf22() throws Exception {
        //scan, parse, and type check the program
        String input = "assignImageAndFrame url u {image i image i1 frame f frame f1\nu -> i -> f -> show; frame f2  \ni -> scale (3) -> f2 -> show; \n i1 <- i; \n f2 <- f;\n}";
        Scanner scanner = new Scanner(input);
        scanner.scan();
        Parser parser = new Parser(scanner);
        ASTNode program = parser.parse();
        TypeCheckVisitor v = new TypeCheckVisitor();
        PLPRuntimeLog.initLog();
        program.visit(v, null);
        show(program);

        //generate code
        CodeGenVisitor cv = new CodeGenVisitor(devel,grade,null);
        byte[] bytecode = (byte[]) program.visit(cv, null);

        //output the generated bytecode
        CodeGenUtils.dumpBytecode(bytecode);

        //write byte code to file
        String name = ((Program) program).getName();
        String classFileName = "bin/" + name + ".class";
        OutputStream output = new FileOutputStream(classFileName);
        output.write(bytecode);
        output.close();
        System.out.println("wrote classfile to " + classFileName);

        // directly execute bytecode
        String[] args = new String[]{"http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg"}; //create command line argument array to initialize params, none in this case
        Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);

        String expOut = "getURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)readFromURL(http://www.gettyimages.com/gi-resources/images/Embed/new/embed2.jpg)createOrSetFrameshowImagescalecreateOrSetFrameshowImagecopyImage";
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream oldStream = System.out;
        System.setOut(new PrintStream(outContent));
        instance.run();
        assertEquals(expOut, PLPRuntimeLog.getString());
        System.out.println(PLPRuntimeLog.getString());
        System.setOut(oldStream);
    }
}

